@WebCalculatorApi_HostAddress = http://localhost:5222

PATCH {{WebCalculatorApi_HostAddress}}/api/serial/ports/COM3
Accept: application/json
Content-Type: application/json
{
  "command": "b"
}
###
PATCH {{WebCalculatorApi_HostAddress}}/api/serial/ports/COM3
Accept: application/json
Content-Type: application/json
{
  "command": "r"
}
###
PATCH {{WebCalculatorApi_HostAddress}}/api/serial/ports/COM3
Accept: application/json
Content-Type: application/json
{
  "command": "?"
}
###
GET {{WebCalculatorApi_HostAddress}}/api/serial/ports