name: Compile Sketches

on:
  - push
  - pull_request

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/arduino/compile-sketches#readme
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          platforms: |
            # Install the platform from the root of the repository, replacing the BM installed platform
            - name: adafruit:avr
              source-url: "https://github.com/adafruit/Adafruit_Arduino_Boards.git"
          fqbn: adafruit:avr:bluefruitmicro
          sketch-paths: |
            - Software/src/CalibrationApp
            - Software/Src/SccApp
          libraries: |
            - source-url: https://github.com/mrstefangrimm/prfServo.git
            - source-url: https://github.com/mrstefangrimm/TemplateStateMachine.git
            - source-path: Software/Src/ParcLib
