name: Compile Sketches

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  compile-sketches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # See: https://github.com/arduino/compile-sketches#readme
      #      https://github.com/arduino/arduino-cli/issues/954
      #      https://adafruit.github.io/arduino-board-index/package_adafruit_index.json 
      #      https://github.com/adafruit/Adafruit_Arduino_Boards/tree/master
      #      https://forum.arduino.cc/t/arduino-cli-cant-find-installed-board-platform/1312333/2
      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: adafruit:samd:adafruit_feather_m0 #adafruit:avr:feather32u4
          platforms: |
            - name: adafruit:samd
              platform: adafruit:samd
              platform_index_url: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
          #platforms: |
            # Install the platform from the root of the repository, replacing the BM installed platform
           # - name: adafruit:avr
          #  source-url: "https://adafruit.github.io/arduino-board-index/package_adafruit_index.json"
        # with:
        #  fqbn: arduino:avr:uno   
          sketch-paths: |
            - Software/src/CalibrationApp
       #     - Software/src/SccApp
          libraries: |
            - source-url: https://github.com/mrstefangrimm/prfServo.git
            - source-url: https://github.com/mrstefangrimm/TemplateStateMachine.git
            - source-url: https://github.com/arduino-libraries/Servo.git
